import type { IconName } from 'angular-ui';
import type { ShowcaseConfig } from '@shared/components/interactive-showcase';
import {
  VARIANTS,
  APPEARANCES,
  SIZES,
  SHAPES,
} from '@shared/utils/showcase/component-options.utils';

export const BUTTON_SHOWCASE_CONFIG: ShowcaseConfig = {
  componentSelector: 'ui-button',
  controlGroups: [
    { id: 'content', label: 'Content', icon: 'text_font' as IconName },
    { id: 'appearance', label: 'Appearance', icon: 'color' as IconName, expanded: true },
    { id: 'layout', label: 'Layout', icon: 'resize' as IconName },
    { id: 'state', label: 'State', icon: 'toggle_left' as IconName },
  ],
  controls: [
    {
      key: 'text',
      label: 'Text',
      type: 'text',
      description: 'Button label text',
      defaultValue: 'Button',
      placeholder: 'Enter button text',
      group: 'content',
    },
    {
      key: 'icon',
      label: 'Icon',
      type: 'dropdown',
      description: 'Icon name',
      options: [
        { value: '', label: 'None' },
        { value: 'star', label: 'star' },
        { value: 'checkmark', label: 'checkmark' },
        { value: 'delete', label: 'delete' },
        { value: 'info', label: 'info' },
        { value: 'settings', label: 'settings' },
        { value: 'home', label: 'home' },
      ],
      defaultValue: '',
      group: 'content',
    },
    {
      key: 'variant',
      label: 'Variant',
      type: 'dropdown',
      description: 'Color variant',
      options: VARIANTS.map(v => ({ value: v, label: v })),
      defaultValue: 'primary',
      group: 'appearance',
    },
    {
      key: 'appearance',
      label: 'Appearance',
      type: 'dropdown',
      description: 'Visual style',
      options: APPEARANCES.map(a => ({ value: a, label: a })),
      defaultValue: 'filled',
      group: 'appearance',
    },
    {
      key: 'size',
      label: 'Size',
      type: 'dropdown',
      options: SIZES.map(s => ({ value: s, label: s })),
      defaultValue: 'medium',
      group: 'layout',
    },
    {
      key: 'shape',
      label: 'Shape',
      type: 'dropdown',
      options: SHAPES.map(s => ({ value: s, label: s })),
      defaultValue: 'rounded',
      group: 'layout',
    },
    {
      key: 'fullWidth',
      label: 'Full Width',
      type: 'switch',
      description: 'Full width button',
      defaultValue: false,
      group: 'layout',
    },
    {
      key: 'disabled',
      label: 'Disabled',
      type: 'switch',
      description: 'Disable button',
      defaultValue: false,
      group: 'state',
    },
    {
      key: 'selectable',
      label: 'Selectable',
      type: 'switch',
      description: 'Click toggles selected state',
      defaultValue: false,
      group: 'state',
    },
    {
      key: 'selected',
      label: 'Selected',
      type: 'switch',
      description: 'Selected state',
      defaultValue: false,
      group: 'state',
    },
    {
      key: 'loading',
      label: 'Loading',
      type: 'switch',
      description: 'Loading state with spinner',
      defaultValue: false,
      group: 'state',
    },
  ],
};
